// <auto-generated />
using System;
using MasaTakip.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MasaTakip.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615122715_AddUserPinAndAdisyonRefactoring")]
    partial class AddUserPinAndAdisyonRefactoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MasaTakip.Domain.Entities.Adisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("KapatanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("MasaId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeTipi")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("OlusturanKullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("KapatanKullaniciId");

                    b.HasIndex("MasaId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Adisyonlar");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.AdisyonDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<int>("AdisyonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AnlikFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<int>("UrunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdisyonId");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("AdisyonDetaylar");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PinCodeHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AktifMi = true,
                            Isim = "Admin",
                            PinCodeHashed = "$2a$11$9O8MUxEh5/h1xrXk5PlIqOsAouW/XD.hQgFnZ4VWpR291M.tPMjIy",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            AktifMi = true,
                            Isim = "Garson 1",
                            PinCodeHashed = "$2a$11$ZYJkWSjyzwRPkEuO1YSHGOShb4wkWpdGGGekt7hCwPxCsi3PWcXvK",
                            Rol = "Garson"
                        },
                        new
                        {
                            Id = 3,
                            AktifMi = true,
                            Isim = "Garson 2",
                            PinCodeHashed = "$2a$11$1dpvAYuwVdqYjSDQ.OIk9OyWK/jiWoUq446OBQvsj4nDVKuzHudQS",
                            Rol = "Garson"
                        });
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Masa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Masalar");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GorselUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Adisyon", b =>
                {
                    b.HasOne("MasaTakip.Domain.Entities.Kullanici", "KapatanKullanici")
                        .WithMany()
                        .HasForeignKey("KapatanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MasaTakip.Domain.Entities.Masa", "Masa")
                        .WithMany("Adisyonlar")
                        .HasForeignKey("MasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasaTakip.Domain.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KapatanKullanici");

                    b.Navigation("Masa");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.AdisyonDetay", b =>
                {
                    b.HasOne("MasaTakip.Domain.Entities.Adisyon", "Adisyon")
                        .WithMany("Detaylar")
                        .HasForeignKey("AdisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasaTakip.Domain.Entities.Kullanici", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasaTakip.Domain.Entities.Urun", "Urun")
                        .WithMany("AdisyonDetaylar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adisyon");

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Urun", b =>
                {
                    b.HasOne("MasaTakip.Domain.Entities.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Adisyon", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Masa", b =>
                {
                    b.Navigation("Adisyonlar");
                });

            modelBuilder.Entity("MasaTakip.Domain.Entities.Urun", b =>
                {
                    b.Navigation("AdisyonDetaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
